/* tslint:disable */
/* eslint-disable */
/**
 * OperationalResearchForEducation API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    TravelingSalesmanProblem,
    TravelingSalesmanProblemFromJSON,
    TravelingSalesmanProblemToJSON,
    TravelingSalesmanSolution,
    TravelingSalesmanSolutionFromJSON,
    TravelingSalesmanSolutionToJSON,
} from '../models';

export interface SolverPostRequest {
    travelingSalesmanProblem?: TravelingSalesmanProblem;
}

/**
 * 
 */
export class SolverApi extends runtime.BaseAPI {

    /**
     */
    async solverPostRaw(requestParameters: SolverPostRequest): Promise<runtime.ApiResponse<TravelingSalesmanSolution>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/Solver`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TravelingSalesmanProblemToJSON(requestParameters.travelingSalesmanProblem),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => TravelingSalesmanSolutionFromJSON(jsonValue));
    }

    /**
     */
    async solverPost(requestParameters: SolverPostRequest): Promise<TravelingSalesmanSolution> {
        const response = await this.solverPostRaw(requestParameters);
        return await response.value();
    }

}
