/* tslint:disable */
/* eslint-disable */
/**
 * OperationalResearchForEducation API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum FirstSolutionStrategy {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15
}

export function FirstSolutionStrategyFromJSON(json: any): FirstSolutionStrategy {
    return FirstSolutionStrategyFromJSONTyped(json, false);
}

export function FirstSolutionStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FirstSolutionStrategy {
    return json as FirstSolutionStrategy;
}

export function FirstSolutionStrategyToJSON(value?: FirstSolutionStrategy | null): any {
    return value as any;
}

