/* tslint:disable */
/* eslint-disable */
/**
 * OperationalResearchForEducation API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FirstSolutionStrategy,
    FirstSolutionStrategyFromJSON,
    FirstSolutionStrategyFromJSONTyped,
    FirstSolutionStrategyToJSON,
} from './';

/**
 * 
 * @export
 * @interface TravelingSalesmanSolution
 */
export interface TravelingSalesmanSolution {
    /**
     * 
     * @type {Array<number>}
     * @memberof TravelingSalesmanSolution
     */
    route?: Array<number> | null;
    /**
     * 
     * @type {number}
     * @memberof TravelingSalesmanSolution
     */
    routeDistance?: number;
    /**
     * 
     * @type {number}
     * @memberof TravelingSalesmanSolution
     */
    distance?: number;
    /**
     * 
     * @type {FirstSolutionStrategy}
     * @memberof TravelingSalesmanSolution
     */
    firstSolutionStrategy?: FirstSolutionStrategy;
}

export function TravelingSalesmanSolutionFromJSON(json: any): TravelingSalesmanSolution {
    return TravelingSalesmanSolutionFromJSONTyped(json, false);
}

export function TravelingSalesmanSolutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TravelingSalesmanSolution {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'route': !exists(json, 'route') ? undefined : json['route'],
        'routeDistance': !exists(json, 'routeDistance') ? undefined : json['routeDistance'],
        'distance': !exists(json, 'distance') ? undefined : json['distance'],
        'firstSolutionStrategy': !exists(json, 'firstSolutionStrategy') ? undefined : FirstSolutionStrategyFromJSON(json['firstSolutionStrategy']),
    };
}

export function TravelingSalesmanSolutionToJSON(value?: TravelingSalesmanSolution | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'route': value.route,
        'routeDistance': value.routeDistance,
        'distance': value.distance,
        'firstSolutionStrategy': FirstSolutionStrategyToJSON(value.firstSolutionStrategy),
    };
}


