/* tslint:disable */
/* eslint-disable */
/**
 * OperationalResearchForEducation API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FirstSolutionStrategy,
    FirstSolutionStrategyFromJSON,
    FirstSolutionStrategyFromJSONTyped,
    FirstSolutionStrategyToJSON,
} from './';

/**
 * 
 * @export
 * @interface TravelingSalesmanProblem
 */
export interface TravelingSalesmanProblem {
    /**
     * 
     * @type {object}
     * @memberof TravelingSalesmanProblem
     */
    distanceMatrix?: object;
    /**
     * 
     * @type {number}
     * @memberof TravelingSalesmanProblem
     */
    numberOfPoints?: number;
    /**
     * 
     * @type {number}
     * @memberof TravelingSalesmanProblem
     */
    startPoint?: number;
    /**
     * 
     * @type {FirstSolutionStrategy}
     * @memberof TravelingSalesmanProblem
     */
    firstSolutionStrategy?: FirstSolutionStrategy;
}

export function TravelingSalesmanProblemFromJSON(json: any): TravelingSalesmanProblem {
    return TravelingSalesmanProblemFromJSONTyped(json, false);
}

export function TravelingSalesmanProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TravelingSalesmanProblem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'distanceMatrix': !exists(json, 'distanceMatrix') ? undefined : json['distanceMatrix'],
        'numberOfPoints': !exists(json, 'numberOfPoints') ? undefined : json['numberOfPoints'],
        'startPoint': !exists(json, 'startPoint') ? undefined : json['startPoint'],
        'firstSolutionStrategy': !exists(json, 'firstSolutionStrategy') ? undefined : FirstSolutionStrategyFromJSON(json['firstSolutionStrategy']),
    };
}

export function TravelingSalesmanProblemToJSON(value?: TravelingSalesmanProblem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'distanceMatrix': value.distanceMatrix,
        'numberOfPoints': value.numberOfPoints,
        'startPoint': value.startPoint,
        'firstSolutionStrategy': FirstSolutionStrategyToJSON(value.firstSolutionStrategy),
    };
}


